name: 'CI'

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  check:
    runs-on: ubuntu-latest
    # TODO: My docker image
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [check]
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    # - name: Upload artifacts
      # uses: actions/upload-artifact@v3
      # with: # ?
        # path: main.out
    - name: Test
      run: ${{github.workspace}}/build/Tests/test
  
  # test:
  #   runs-on: ubuntu-latest
  #   container: leshiy1295/gcc_linters_valgrind_cmake_gtest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: make test
      