name: 'CI'

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug
  RUN_MEMORY_CHECK: ${{ (secrets.RUN_MEMORY_CHECK == 'true') }}

jobs:
  check-style:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3
      - run: ./run_linters.sh
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B "$GITHUB_WORKSPACE"/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build App and Tests
        run: cmake --build "$GITHUB_WORKSPACE"/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd "$GITHUB_WORKSPACE"/build; ctest -C ${{env.BUILD_TYPE}}

      - run: pwd
#      - run: ls -lah ${{github.workspace}}
      - run: ls -lah "$GITHUB_WORKSPACE"
      - run: ls -lah

      - echo: "$GITHUB_WORKSPACE"
      - echo: $GITHUB_WORKSPACE

      - name: Upload test 2
        uses: actions/upload-artifact@v3
        with:
          name: test2
          path: "\"$GITHUB_WORKSPACE\"/build"

      - name: Upload test 3
        uses: actions/upload-artifact@v3
        with:
          name: test3
          path: "\"$GITHUB_WORKSPACE\"/build"

      - name: Upload test 5
        uses: actions/upload-artifact@v3
        with:
          name: test5
          path: "\"$GITHUB_WORKSPACE\"/build"

      - run: cd "$GITHUB_WORKSPACE"
      - name: Upload test 4
        uses: actions/upload-artifact@v3
        with:
          name: test4
          path: ./build
  check-memory:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Download test
        uses: actions/download-artifact@v3
        with:
          name: test
          path: ./build/Tests

#      - name: PWD
#        run: pwd
#
#      - name: LS
#        run: ls -lah ${{github.workspace}}
#
#      - name: LS
#        run: ls -lah ${{github.workspace}}/build
#
#      - name: LS
#        run: ls -lah ${{github.workspace}}/build/Tests

      - name: Run Tests with Valgrind
        run: valgrind --tool=memcheck --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./build/Tests/Tests &> /dev/null

      - name: Valgrind Memory check
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          echo "Checking Valgrind xml ..."
            ./check_memory.sh