name: 'CI'

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug
  RUN_MEMORY_CHECK: ${{ (secrets.RUN_MEMORY_CHECK == 'true') }}
  WORK_DIR: $GITHUB_WORKSPACE

jobs:
  static_analyze:
    runs-on: ubuntu-latest
    container: vvinokurshin/project_cpp:v1
    steps:
      - uses: actions/checkout@v3
      - run: ./run_linters.sh
  build:
    runs-on: ubuntu-latest
    container: vvinokurshin/project_cpp:v1
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{env.WORK_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build App and Tests
        run: cmake --build ${{env.WORK_DIR}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{env.WORK_DIR}}/build; ctest --output-on-failure -C ${{env.BUILD_TYPE}}; cd ${{env.WORK_DIR}}

      - name: Upload test
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ./build/Tests

      - name: Generate coverage.info
        run: lcov -t "TestsCoverage" -o coverage.info -c -d build/Tests/CMakeFiles/Tests.dir/__/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.info
  check-memory:
    runs-on: ubuntu-latest
    container: vvinokurshin/project_cpp:v1
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - name: Download test
        uses: actions/download-artifact@v3
        with:
          name: test
          path: ./build/Tests

      - run: chmod +x ./build/Tests/Tests

      - name: Run Tests with Valgrind
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: valgrind --tool=memcheck --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./build/Tests/Tests >/dev/null 2>&1

      - name: Valgrind Memory check
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          echo "Checking Valgrind xml ..."
            ./check_memory.sh
