name: 'CI'

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug
  RUN_MEMORY_CHECK: ${{ (secrets.RUN_MEMORY_CHECK == 'true') }}
  WORK_DIR: $GITHUB_WORKSPACE

jobs:
#  check-style:
#    runs-on: ubuntu-latest
#    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
#    steps:
#      - uses: actions/checkout@v3
#      - run: ./run_linters.sh
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{env.WORK_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build App and Tests
        run: cmake --build ${{env.WORK_DIR}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{env.WORK_DIR}}/build; ctest -C ${{env.BUILD_TYPE}}; cd ${{env.WORK_DIR}}

      - name: Upload test
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ./build/Tests
  check-memory:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - name: Download test
        uses: actions/download-artifact@v3
        with:
          name: test
          path: ./build/Tests

      - run: ./build/Tests/Tests >/dev/null 2>&1

      - name: Run Tests with Valgrind
        run: valgrind --tool=memcheck --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./build/Tests/Tests >/dev/null 2>&1

      - name: Valgrind Memory check
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          echo "Checking Valgrind xml ..."
            ./check_memory.sh